/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Stake } from "./Stake";
export * as factories from "./factories";
export { Stake__factory } from "./factories/Stake__factory";
